version: '3'
services:
  evalua:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - database
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: evalua
      MYSQL_ROOT_PASSWORD: ''
    ports:
      - '3306:3306'
